name: lisp

on:
  push:
    branches: [ main, master ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install SBCL
        run: |
          sudo apt-get update
          sudo apt-get install -y sbcl

      - name: Run launcher tests
        run: sbcl --script tests/launcher_test.lisp

